name: base_beckend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  shelf: ^1.4.0
  mysql1: ^0.20.0
  shelf_router: ^1.1.3  